-- ----------------------------------------------------
-- 💼 AutoApply Pro: Supabase Database Schema Setup
-- ----------------------------------------------------

-- Enable UUID extension if not already enabled
create extension if not exists "uuid-ossp";

-- ── 1. CANDIDATE PROFILES TABLE ─────────────────────
-- Stores user contact details, target job search queries, resume text, and private API keys.
-- Each row corresponds directly to a user in Supabase Auth (auth.users).
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text,
  phone text,
  address text,
  city text,
  github_url text,
  linkedin_url text,
  search_criteria jsonb default '{}'::jsonb,
  skills text[] default '{}'::text[],
  encrypted_groq_key text,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable Row-Level Security
alter table public.profiles enable row level security;

-- Policies: Users can only select or update their own profile record.
create policy "Users can view own profile" 
  on public.profiles for select 
  using (auth.uid() = id);

create policy "Users can update own profile" 
  on public.profiles for update 
  using (auth.uid() = id);


-- ── 2. JOB APPLICATIONS LOG TABLE ───────────────────
-- Relational table logging all successfully submitted job applications.
create table public.applications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  job_title text not null,
  company text not null,
  location text,
  cover_letter text,
  job_description text,
  status text default 'Applied'::text not null,
  applied_date timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row-Level Security
alter table public.applications enable row level security;

-- Policies: Users can perform CRUD operations only on their own application logs.
create policy "Users can view own applications" 
  on public.applications for select 
  using (auth.uid() = user_id);

create policy "Users can insert own applications" 
  on public.applications for insert 
  with check (auth.uid() = user_id);

create policy "Users can update own applications" 
  on public.applications for update 
  using (auth.uid() = user_id);

create policy "Users can delete own applications" 
  on public.applications for delete 
  using (auth.uid() = user_id);


-- ── 3. AUTOMATIC PROFILE GENERATION TRIGGER ──────────
-- Automatically provisions a blank profile row whenever a new user registers an account.
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, search_criteria, skills)
  values (new.id, '', '{}'::jsonb, '{}'::text[]);
  return new;
end;
$$ language plpgsql security definer;

-- Trigger mapping trigger function to auth.users insert event
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- ── 4. BOT EVENTS TABLE (REAL-TIME SYNC) ──────────────
-- Relational table logging all real-time events from the Playwright bot or Chrome Extension.
create table public.bot_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  event_type text not null, -- 'log', 'navigating', 'typing', 'clicking', 'mismatch', 'success'
  payload jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row-Level Security
alter table public.bot_events enable row level security;

-- Policies: Users can perform CRUD operations only on their own bot events.
create policy "Users can view own bot events" 
  on public.bot_events for select 
  using (auth.uid() = user_id);

create policy "Users can insert own bot events" 
  on public.bot_events for insert 
  with check (auth.uid() = user_id);

create policy "Users can delete own bot events" 
  on public.bot_events for delete 
  using (auth.uid() = user_id);

